//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string bill_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string employee_id { get; set; }
        public string voucher_id { get; set; }
        public Nullable<int> bill_price { get; set; }
        public Nullable<int> off_money { get; set; }
        public Nullable<int> total_money { get; set; }
    }
}
