//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public byte[] product_img { get; set; }
        public int price { get; set; }
        public System.DateTime update_date { get; set; }
        public string detail { get; set; }
    }
}
