//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        public string voucher_id { get; set; }
        public int apply_price { get; set; }
        public Nullable<double> off_percent { get; set; }
        public Nullable<bool> used { get; set; }
    }
}
